Increment3
Svetopolk/shortener pull request #3
Opened 2022-07-08 18:52 UTC by Svetopolk

2022-07-12 19:03 UTC, capsulated requested changes
Кое что необходимо исправить

2022-07-12 19:03 UTC, capsulated commented on cmd/shortener/main.go
> +		hash := trimFirstRune(r.URL.Path)
Вопрос с намёком: а почему Rune? ))) Метод излишний, используется один раз и обёрнут в функцию. И всё же, почему именно Rune? )))

2022-07-12 19:03 UTC, capsulated commented on cmd/shortener/storage.go
> +	return "dfdsavarevw"
😱

2022-07-12 19:03 UTC, capsulated commented on cmd/shortener/storage.go
> +	return "dfdsavarevw"
Промежуточный неработающий код комитить не нужно. В реальных проектах тим-лид за такое скажет что-то нехорошее ))))

2022-07-12 19:03 UTC, capsulated commented on cmd/shortener/storage.go
> +	return "https://example.com/"
😱 промежуточные комиты не пушим - нужно squash-ить )

2022-07-12 19:03 UTC, capsulated commented on cmd/shortener/util.go
> +func RandStringRunes(n int) string {
А если повториться hash? )

2022-07-12 19:03 UTC, capsulated commented on cmd/shortener/handler.go
Что-то папка internal пустая, всё в cmd 😭

2022-07-12 19:03 UTC, capsulated commented on cmd/shortener/main.go
> +func NewRouter(m RequestHandler) chi.Router {
NewRouter() в main лучше не добавлять - хорошая практика создавать отдельные пакеты для сервера с роутером, для хранения и тд.

2022-07-12 19:03 UTC, capsulated commented on cmd/shortener/handler.go
> -	fullUrl := h.storage.get(hash)
А я больше так люблю именовать переменные, к примеру ProductId =) Но это просто комментарий )))

2022-07-13 13:33 UTC, Svetopolk commented on cmd/shortener/storage.go
> +	return "https://example.com/"
за-squash-им когда будем сливать в мастер

2022-07-13 13:37 UTC, Svetopolk commented on cmd/shortener/main.go
> +		hash := trimFirstRune(r.URL.Path)
стринги же состоят из рун, они же символы. надо было отрезать 1 символ. В данном случае отрезаем слеш, который кодируется одним байтом ... в принципе можно было отрезать 1 байн, а не руну. Но вдруг пригодится отрезать еще что нибудь ...

2022-07-13 13:37 UTC, Svetopolk commented on cmd/shortener/storage.go
> +	return "dfdsavarevw"
смотря какой тим-лид. Хорошо что у нас тут нет таких :)

2022-07-13 19:40 UTC, Svetopolk commented on cmd/shortener/util.go
> +func RandStringRunes(n int) string {
исправил

2022-07-14 15:15 UTC, capsulated commented on cmd/shortener/main.go
> +		hash := trimFirstRune(r.URL.Path)
все стринги состоят из рун?

2022-07-14 16:05 UTC, capsulated requested changes
Необходимы изменения

2022-07-14 16:05 UTC, capsulated commented on internal/app/service/shortService_test.go
> +var _ storage.Storage = &MockStorage{}
Для чего здесь эта строка?

2022-07-14 16:05 UTC, capsulated commented on internal/app/storage/memStorage.go
> +var _ Storage = &MemStorage{}
Тоже самое, с какой целью создаётся пустая переменная?

2022-07-14 16:05 UTC, capsulated commented on internal/app/storage/memStorage.go
> +	s.mapStore[hash] = url
Если создать несколько потоков (например, создать 1000 параллельно работающих клиентов), которые будут использовать сервис создания коротких url, будет ли всё корректно работать? Целостность данных не нарушится?

Вопрос наводящий, тут ошибка, так мапы использовать нельзя.

2022-07-14 16:05 UTC, capsulated commented on internal/app/service/shortService.go
> +func NewShortService(storage storage.Storage) ShortService {
NewShortService() возвращает экземпляр структуры, а NewMemStorage() возвращает указатель на структуру. В чём причина такого различия? В каком случае нужно возвращать экземпляр, а в каком указатель?

2022-07-14 16:05 UTC, capsulated commented on internal/app/rest/handler.go
> +func NewRequestHandler(storage service.ShortService) RequestHandler {
В параметре тип - структура. В NewShortService в параметрах - интерфейс. Нужно привести к единому виду - либо всё на интерфейсах, либо всё через структуры. 

Также, в параметрах экземпляр структуры? И возвращает функция также экземпляр? Если непонятен мой вопрос, то опять же необходимо ответить на другой: 
"Когда необходимо использовать экземпляр, а когда указатель?"

2022-07-14 16:05 UTC, capsulated commented on internal/app/rest/handler.go
>  func (h *RequestHandler) handlePost(w http.ResponseWriter, r *http.Request) {
В чтении body ошибка. Код не видно в ревью строки чтения, не могу поставить комментарий. Проверьте пожалуйста.

2022-07-14 16:05 UTC, capsulated commented on internal/app/rest/handler.go
> +	fullURL := h.storage.Get(hash)
Если storage.Get() вернёт пустое значение?

2022-07-14 16:05 UTC, capsulated commented on internal/app/util/util.go
> +func RemoveFirstSymbol(s string) string {
Для чего отдельная функция? Единственная операция в одну строку обёрнута в функцию и используется в одном месте программы. Переизбыточно, усложняет читаемость кода без причины.

2022-07-14 16:05 UTC, capsulated commented on internal/app/util/util.go
>  	b := make([]rune, n)
Опять же, rune - переизбыточно. Почему руна? Когда используются руны?

2022-07-15 07:42 UTC, Svetopolk commented on internal/app/service/shortService_test.go
> +var _ storage.Storage = &MockStorage{}
так рекомендовал Фоломкин на семинаре, как проверка, что структура удовлетворяет интерфейсу

2022-07-15 07:42 UTC, Svetopolk commented on internal/app/storage/memStorage.go
> +var _ Storage = &MemStorage{}
ответил выше, это такой хитрый прием

2022-07-15 07:44 UTC, Svetopolk commented on internal/app/storage/memStorage.go
> +	s.mapStore[hash] = url
это точно наводящий вопрос к 3 инкременту? 
я предполагал что эта тема будет рассказана позже

2022-07-15 07:47 UTC, Svetopolk commented on internal/app/rest/handler.go
> +	fullURL := h.storage.Get(hash)
будет редирект на пустой урл... в задании не сказано как надо обрабатывать такие случаи.. кидать ли 400 ошибку или делать редирект в пустоту или еще что ... поэтому я не стал мудрить. Тесты же проходят

2022-07-15 07:49 UTC, Svetopolk commented on internal/app/util/util.go
> +func RemoveFirstSymbol(s string) string {
ну такое бывает, когда функция используется в 1 месте. это не такая уж редкость
 А название RemoveFirstSymbol добавляет смысла ... не надо всматриваться в индексы которые указаны в слайсе и нет ли там ошибки, просто можно прочитать название процедуры. Читаемость кода упрощается.

2022-07-15 08:09 UTC, Svetopolk commented on internal/app/service/shortService.go
> +func NewShortService(storage storage.Storage) ShortService {
Я вначале возвращал интерфейс ... потом посмотрел что вроде как принято возвращать структуру, да? 
А указателя на интерфейс не бывает, если я правильно понимаю ... ну там  нет звездочки ... и когда переделывал на структуру, то про звездочки забыл. Вообще как то неудобно получается, надо постоянно следить, что перед тобой интерфейс или структура что бы то ставить звездочку, а то нет.

2022-07-15 10:52 UTC, Svetopolk commented on internal/app/rest/handler.go
> +func NewRequestHandler(storage service.ShortService) RequestHandler {
поправил

2022-07-15 11:01 UTC, Svetopolk commented on internal/app/util/util.go
>  	b := make([]rune, n)
переделал на byte

2022-07-15 11:03 UTC, Svetopolk commented on cmd/shortener/main.go
> +func NewRouter(m RequestHandler) chi.Router {
перенес

2022-07-15 11:03 UTC, Svetopolk commented on cmd/shortener/handler.go
поправил

2022-07-15 11:04 UTC, Svetopolk commented on cmd/shortener/main.go
> +		hash := trimFirstRune(r.URL.Path)
поправил

2022-07-15 12:47 UTC, Svetopolk commented on internal/app/rest/handler.go
>  func (h *RequestHandler) handlePost(w http.ResponseWriter, r *http.Request) {
не понимаю о какой баге идет речь ...
а почему нет строки? ... ну в ПР на закладке файл полный текст файла handler.go

2022-07-15 20:52 UTC, capsulated commented on cmd/shortener/storage.go
> +	return "dfdsavarevw"
не не, промежуточные комиты никто не разрешает) их можно soft reset и заново закомитить, или squash

2022-07-15 21:31 UTC, capsulated commented on internal/app/service/shortService_test.go
> +var _ storage.Storage = &MockStorage{}
👌

2022-07-15 21:31 UTC, capsulated commented on internal/app/storage/memStorage.go
> +	s.mapStore[hash] = url
👌 оставляем

2022-07-15 21:34 UTC, capsulated commented on internal/app/service/shortService.go
> +func NewShortService(storage storage.Storage) ShortService {
Лучше в одном единственном месте создавать структуру и передавать везде указатель, чтобы не дублировать экземпляры при передаче. Особенно, если в структуре много байт разных данных, то копирование может привести к утечкам памяти. 

Если посмотреть в стандартные библиотеки go, то можно увидеть, что во многих пакетах конструкторы возвращают указатель на созданную структуру.

2022-07-15 21:35 UTC, capsulated commented on internal/app/rest/handler.go
> +func NewRequestHandler(storage service.ShortService) RequestHandler {
В комменте выше описал причину.

2022-07-15 21:38 UTC, capsulated commented on internal/app/rest/handler.go
>  func (h *RequestHandler) handlePost(w http.ResponseWriter, r *http.Request) {
Вот и сложность с комитами... )

Там поток body не закрыт. Тоже, получается, двусмысленная ситуация - вроде ошибки и нет, и тесты проходят и error'ов нет, а утечка памяти есть. Go очень класcно приучает заботиться о ресурсах - процессорном времени и памяти и оценивать производительность в этих категориях.

2022-07-15 21:45 UTC, capsulated commented on internal/app/util/util.go
> +func RemoveFirstSymbol(s string) string {
Функцию обычно создают для избавления от повторяющегося кода - это принцип [DRY](https://habr.com/ru/post/144611/). Если он не повторяется - то функцию создавать избыточно. А если она состоит из одной строки - то точно не нужно, можно везде заменить вызов функции одной строкой. Вся эта история относиться к первому принципу SOLID и Clean Code.

2022-07-15 21:47 UTC, capsulated commented on cmd/shortener/storage.go
> +	return "https://example.com/"
Можно [soft reset](https://habr.com/ru/post/203282/)

2022-07-15 21:49 UTC, capsulated commented on internal/app/service/shortService.go
> +func NewShortService(storage storage.Storage) ShortService {
Лучше указатель экземпляра, и везде его использовать, так как по сути единственный экземпляр его используем.

2022-07-15 21:54 UTC, capsulated commented on internal/app/util/util.go
>  	b := make([]rune, n)
Руна - двухбайтовая, для unicode'а. Если мы не используем различные символы, типа кириллицы, иероглифы и т.п., то это стандартная однобайтовая ASCII кодировка. И для неё руны не нужны. Но, если в слайс letterRunes добавить кириллицу, иврит или арабские символы и т.п.- то эти символы кодируются уже двумя байтами, и использование рун будет обязательно.

2022-07-15 22:00 UTC, capsulated commented
Оставил коменты, если есть желание добиться более читаемого кода и не забывать об аллокации памяти.

2022-07-15 22:03 UTC, capsulated requested changes
Поток body не закрыт 😣 Не могу принять. На остальное можно вообщем закрыть глаза, хотя указателями тоже нужно потренироваться... Но body не закрытый - грубая ошибка.

2022-07-15 23:53 UTC, capsulated commented on internal/app/rest/handler.go
> +	fullURL := h.storage.Get(hash)
👌

2022-07-18 07:32 UTC, Svetopolk commented on internal/app/rest/handler.go
>  func (h *RequestHandler) handlePost(w http.ResponseWriter, r *http.Request) {
ок, закрыл  r.Body.Close()

2022-07-18 07:44 UTC, Svetopolk commented on cmd/shortener/storage.go
> +	return "dfdsavarevw"
ну это разные подходы... твой какой то устарелый  
В той ссылке что ты кидал https://habr.com/ru/company/vk/blog/572560/ 
ни слова нет про код ревью ... потому что он в эту концепцию "значально правильных коммитов" вообще не вписывается. 

В общем когда буду вливать в мастер поставлю галочку squash и в мастере будет 1 правильный коммит. Надеюсь ты останешься доволен и вопрос закрыт

2022-07-18 07:49 UTC, Svetopolk commented on internal/app/util/util.go
> +func RemoveFirstSymbol(s string) string {
ну нет... функцию создают НЕ ТОЛЬКО для избавления от повторяющегося кода. И запрета на существование функции в 1 строчку я тоже не встречал. Моя функция RemoveFirstSymbol с понятным самоописывающимся названием полностью удовлетворяет концепции Clean Code

2022-07-18 07:51 UTC, Svetopolk commented on internal/app/rest/handler.go
>  func (h *RequestHandler) handlePost(w http.ResponseWriter, r *http.Request) {
ок, поток закрыл

2022-07-18 16:09 UTC, capsulated approved these changes

2022-07-18 16:09 UTC, capsulated commented on internal/app/rest/handler.go
>  func (h *RequestHandler) handlePost(w http.ResponseWriter, r *http.Request) {
Да, конечно можно, но в комите не было этой строки, и я не мог оставить коментарий.

2022-07-19 06:38 UTC, Svetopolk commented on internal/app/service/shortService.go
> +func NewShortService(storage storage.Storage) ShortService {
поправил

2022-07-19 06:39 UTC, Svetopolk commented on internal/app/rest/handler.go
> +func NewRequestHandler(storage service.ShortService) RequestHandler {
исправил

2022-07-19 07:57 UTC, merged